# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5941f8949fd7e0642fc626fc961b1e9c91506a1bab1768384cf03e5fb4a3b42a0948bf95d766a7416a12b33c1a6df1e455d6fbf47700e7bd15b55b998becee93

test:
  secret_key_base: ed76627c1c76483861aa8144c5a44207d95d3f5b6604cae99cb375c858a24d1342690b9ec658b15090a8b786e416bd7e6cfccd6189ffde3800b5d8149bd4e294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
